[profile.release]
lto = true

[workspace]
members = [
  "lib/",
  "examples/hello",
  "examples/json",
  "examples/proxy",
  "examples/state",
  "examples/responder",
  "examples/redirect",
  "examples/templates_askama",
]
