[package]
name = "proxy"
version = "0.0.0"
workspace = "../.."

[dependencies]
shio = { path = "../../lib", features = ["nightly"] }
hyper = "0.11"
futures-await = { git = 'https://github.com/alexcrichton/futures-await' }
