[package]
name = "json"
version = "0.0.0"
workspace = "../.."

[dependencies]
shio = { path = "../../lib" }
tokio-io = "0.1.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
error-chain = "0.11.0-rc.2"
futures-await = { git = 'https://github.com/alexcrichton/futures-await' }
